# Generated by Django 6.0.1 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('salon', 'Salon'), ('consult', 'Consultancy')], default='doctor', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
