# Generated by Django 6.0.1 on 2026-03-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_payment_id_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
