# Generated by Django 6.0.1 on 2026-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_service_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
